# DESCRIPTION: Github actions config
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

name: MT check

on:
  push:
  pull_request_target:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04 | MT check
    env:
      CI_OS_NAME: linux
      CI_RUNS_ON: ubuntu-22.04
      CI_COMMIT: ${{ github.sha }}
      CI_M32: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install packages for build
        env:
          CI_BUILD_STAGE_NAME: build
        run: |
          bash ci/ci-install.bash &&
          sudo apt-get install clang-14 libclang-14-dev
          pip install clang==14.0.0 termcolor
      - name: Check MT attributes
        run: |
          python ci/clang_check_attributes.py src/V3EmitCImp.cpp -Isrc/ -Iinclude/ -Isrc/obj_opt/ -x std::,__builtin_,AstNode::accept,__gnu_cxx
